# 2024-2025 Project: NYC-Trip-Fare

**1) Extract all trips with trip_distance larger than 50**

In [1]:
import pandas as pd

# Si carica il dataset
df = pd.read_csv("data.csv", low_memory=False)

# Si estraggono i viaggi con trip_distance > 50
long_trips = df[df["trip_distance"] > 50]

# Si mostrano i risultati
long_trips

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge
23842,2.0,2020-01-01 01:53:07,2020-01-01 03:54:41,1.0,52.30,5.0,N,262,265,1.0,300.00,0.00,0.0,61.78,6.12,0.3,370.70,2.5
39013,2.0,2020-01-01 02:05:07,2020-01-01 03:03:10,1.0,51.23,5.0,N,264,264,1.0,329.00,0.00,0.5,100.78,6.12,0.3,436.70,0.0
41620,1.0,2020-01-01 03:05:54,2020-01-01 04:16:26,1.0,53.80,5.0,N,132,265,1.0,250.00,0.00,0.0,53.35,16.62,0.3,320.27,0.0
58262,2.0,2020-01-01 05:36:12,2020-01-01 06:40:06,1.0,55.23,5.0,N,132,265,2.0,170.00,0.00,0.5,0.00,18.26,0.3,189.06,0.0
63024,2.0,2020-01-01 07:40:30,2020-01-01 08:40:01,1.0,54.19,5.0,N,132,265,1.0,230.00,0.00,0.0,0.00,12.24,0.3,242.54,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6326169,2.0,2020-01-31 22:47:26,2020-01-31 23:49:14,1.0,51.83,5.0,N,132,265,1.0,220.00,0.00,0.5,48.96,23.99,0.3,293.75,0.0
6331181,2.0,2020-01-31 23:45:36,2020-02-01 01:00:25,5.0,57.99,4.0,N,107,265,1.0,245.00,0.50,0.5,38.24,6.12,0.3,293.16,2.5
6333801,2.0,2020-01-31 23:24:16,2020-02-01 01:32:56,1.0,52.97,4.0,N,264,265,1.0,227.00,0.50,0.5,46.16,0.00,0.3,276.96,2.5
6397132,NaN,2020-01-28 11:54:00,2020-01-28 19:35:00,NaN,60.36,NaN,NaN,17,61,NaN,12.04,0.00,0.5,0.00,12.24,0.3,25.08,0.0
6398446,NaN,2020-01-28 07:37:00,2020-01-28 08:42:00,NaN,210240.07,NaN,NaN,76,231,NaN,37.77,2.75,0.5,0.00,0.00,0.3,41.32,0.0

In [ ]:
# low_memory=False consente di non avere warning di low memory in fase di esecuzione del codice

**2) Extract all trips where payment_type is missing**

In [1]:
import pandas as pd

# Si carica il dataset
df = pd.read_csv("data.csv", low_memory=False)

# Si estraggoni i viaggi con payment_type mancante
missing_payment = df[df["payment_type"].isna()]

# Si visualizzano i risultati
missing_payment

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge
6339567,NaN,2020-01-01 08:51:00,2020-01-01 09:19:00,NaN,13.69,NaN,NaN,136,232,NaN,51.05,2.75,0.5,0.0,0.00,0.3,54.60,0.0
6339568,NaN,2020-01-01 08:38:43,2020-01-01 08:51:08,NaN,3.42,NaN,NaN,121,9,NaN,27.06,2.75,0.0,0.0,0.00,0.3,30.11,0.0
6339569,NaN,2020-01-01 08:27:00,2020-01-01 08:32:00,NaN,2.20,NaN,NaN,197,216,NaN,24.36,2.75,0.5,0.0,0.00,0.3,27.91,0.0
6339570,NaN,2020-01-01 08:46:00,2020-01-01 08:57:00,NaN,0.84,NaN,NaN,262,236,NaN,26.08,2.75,0.5,0.0,0.00,0.3,29.63,0.0
6339571,NaN,2020-01-01 08:21:00,2020-01-01 08:38:00,NaN,7.24,NaN,NaN,45,142,NaN,25.28,2.75,0.5,0.0,0.00,0.3,28.83,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6405003,NaN,2020-01-31 22:51:00,2020-01-31 23:22:00,NaN,3.24,NaN,NaN,237,234,NaN,17.59,2.75,0.5,0.0,0.00,0.3,21.14,0.0
6405004,NaN,2020-01-31 22:10:00,2020-01-31 23:26:00,NaN,22.13,NaN,NaN,259,45,NaN,46.67,2.75,0.5,0.0,12.24,0.3,62.46,0.0
6405005,NaN,2020-01-31 22:50:07,2020-01-31 23:17:57,NaN,10.51,NaN,NaN,137,169,NaN,48.85,2.75,0.0,0.0,0.00,0.3,51.90,0.0
6405006,NaN,2020-01-31 22:25:53,2020-01-31 22:48:32,NaN,5.49,NaN,NaN,50,42,NaN,27.17,2.75,0.0,0.0,0.00,0.3,30.22,0.0
6405007,NaN,2020-01-31 22:44:00,2020-01-31 23:06:00,NaN,11.60,NaN,NaN,179,205,NaN,54.56,2.75,0.5,0.0,0.00,0.3,58.11,0.0

In [ ]:
#

**3) For each (PULocationID, DOLocationID) pair, determine the number of trips**

In [2]:
# Si contano i viaggi per ogni coppia (PULocationID, DOLocationID)
trip_counts = df.groupby(["PULocationID", "DOLocationID"]).size().reset_index(name="trip_count")

# Si ordinano i risultati per numero di viaggi (dal più frequente al meno frequente):
trip_counts = trip_counts.sort_values(by="trip_count", ascending=False)

# Si visualizzano i risultati
trip_counts

       PULocationID  DOLocationID  trip_count
27648           237           236       45539
27408           236           236       38775
27409           236           237       38264
27649           237           237       33909
31160           264           264       27928
...             ...           ...         ...
8692             80           108           1
549               9            70           1
25679           229             6           1
18890           163           245           1
4635             47           262           1

[31277 rows x 3 columns]

**4) Save all rows with missing VendorID, passenger_count, store_and_fwd_flag, payment_type in a new dataframe called bad, and remove those rows from the original dataframe.**

In [3]:
# Si crea un dataframe con le righe non pulite
bad = df[df[["VendorID", "passenger_count", "store_and_fwd_flag", "payment_type"]].isna().any(axis=1)]

# Si rimuovono tali righe dal dataframe originale
df = df.drop(bad.index)

# Si mostrano le righe del dataset ora pulito dalle righe difettose
df

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge
0,1.0,2020-01-01 00:28:15,2020-01-01 00:33:03,1.0,1.20,1.0,N,238,239,1.0,6.0,3.0,0.5,1.47,0.0,0.3,11.27,2.5
1,1.0,2020-01-01 00:35:39,2020-01-01 00:43:04,1.0,1.20,1.0,N,239,238,1.0,7.0,3.0,0.5,1.50,0.0,0.3,12.30,2.5
2,1.0,2020-01-01 00:47:41,2020-01-01 00:53:52,1.0,0.60,1.0,N,238,238,1.0,6.0,3.0,0.5,1.00,0.0,0.3,10.80,2.5
3,1.0,2020-01-01 00:55:23,2020-01-01 01:00:14,1.0,0.80,1.0,N,238,151,1.0,5.5,0.5,0.5,1.36,0.0,0.3,8.16,0.0
4,2.0,2020-01-01 00:01:58,2020-01-01 00:04:16,1.0,0.00,1.0,N,193,193,2.0,3.5,0.5,0.5,0.00,0.0,0.3,4.80,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6339562,2.0,2020-01-31 23:38:07,2020-01-31 23:52:21,1.0,2.10,1.0,N,163,246,1.0,11.0,0.5,0.5,2.96,0.0,0.3,17.76,2.5
6339563,2.0,2020-01-31 23:00:18,2020-01-31 23:19:18,1.0,2.13,1.0,N,164,79,1.0,13.0,0.5,0.5,3.36,0.0,0.3,20.16,2.5
6339564,2.0,2020-01-31 23:24:22,2020-01-31 23:40:39,1.0,2.55,1.0,N,79,68,1.0,12.5,0.5,0.5,3.26,0.0,0.3,19.56,2.5
6339565,2.0,2020-01-31 23:44:22,2020-01-31 23:54:00,1.0,1.61,1.0,N,100,142,2.0,8.5,0.5,0.5,0.00,0.0,0.3,12.30,2.5
6339566,2.0,2020-01-31 23:19:37,2020-01-31 23:20:41,1.0,0.00,1.0,N,193,193,1.0,0.0,0.0,0.0,0.00,0.0,0.0,0.00,0.0

**5) Add a duration column storing how long each trip has taken (use tpep_pickup_datetime, tpep_dropoff_datetime)**

In [4]:
import pandas as pd

# Ci si assicura che le date siano in formato datetime
df["tpep_pickup_datetime"] = pd.to_datetime(df["tpep_pickup_datetime"])
df["tpep_dropoff_datetime"] = pd.to_datetime(df["tpep_dropoff_datetime"])

# Si calcola la durata
df["duration_timedelta"] = df["tpep_dropoff_datetime"] - df["tpep_pickup_datetime"]

# Si estraggono giorni, ore, minuti e secondi
duration_components = df["duration_timedelta"].dt.components
df["duration"] = (
    duration_components["days"].astype(str) + "d " +
    duration_components["hours"].astype(str) + "h " +
    duration_components["minutes"].astype(str) + "m " +
    duration_components["seconds"].astype(str) + "s"
)

# Si visualizzano i risultati
df[["tpep_pickup_datetime", "tpep_dropoff_datetime", "duration"]]

        tpep_pickup_datetime tpep_dropoff_datetime       duration
0        2020-01-01 00:28:15   2020-01-01 00:33:03   0d 0h 4m 48s
1        2020-01-01 00:35:39   2020-01-01 00:43:04   0d 0h 7m 25s
2        2020-01-01 00:47:41   2020-01-01 00:53:52   0d 0h 6m 11s
3        2020-01-01 00:55:23   2020-01-01 01:00:14   0d 0h 4m 51s
4        2020-01-01 00:01:58   2020-01-01 00:04:16   0d 0h 2m 18s
...                      ...                   ...            ...
6339562  2020-01-31 23:38:07   2020-01-31 23:52:21  0d 0h 14m 14s
6339563  2020-01-31 23:00:18   2020-01-31 23:19:18   0d 0h 19m 0s
6339564  2020-01-31 23:24:22   2020-01-31 23:40:39  0d 0h 16m 17s
6339565  2020-01-31 23:44:22   2020-01-31 23:54:00   0d 0h 9m 38s
6339566  2020-01-31 23:19:37   2020-01-31 23:20:41    0d 0h 1m 4s

[6339567 rows x 3 columns]

**6) For each pickup location, determine how many trips have started there.**

In [5]:
# Si contano quante corse sono partite da ciascuna pickup location
pickup_counts = df.groupby('PULocationID').size().reset_index(name='trip_count')

# Si ordinano in ordine decrescente
pickup_counts = pickup_counts.sort_values(by='trip_count', ascending=False)

# Si visualizzano le righe
pickup_counts

     PULocationID  trip_count
231           237      292467
156           161      281545
230           236      271999
157           162      235024
181           186      228231
..            ...         ...
101           105           2
239           245           1
28             30           1
198           204           1
167           172           1

[260 rows x 2 columns]

In [ ]:
#

**7) Cluster the pickup time of the day into 30-minute intervals (e.g. from 02:00 to 02:30)**

In [6]:
import pandas as pd

# Si carica il dataset
df = pd.read_csv("data.csv", low_memory=False)

# Ci si assicura che il campo datetime sia nel formato corretto
df["tpep_pickup_datetime"] = pd.to_datetime(df["tpep_pickup_datetime"])

# Si estraggono ore e minuti, poi si calcola la fascia oraria da 30 minuti
def cluster_pickup_time(dt):
    hour = dt.hour
    minute = dt.minute
    if minute < 30:
        return f"{hour:02d}:00 - {hour:02d}:30"
    else:
        next_hour = (hour + 1) % 24
        return f"{hour:02d}:30 - {next_hour:02d}:00"

# Si applica la funzione al dataset
df["pickup_time_interval"] = df["tpep_pickup_datetime"].apply(cluster_pickup_time)

# Si visualizza i risultati
df[["tpep_pickup_datetime", "pickup_time_interval"]]

        tpep_pickup_datetime pickup_time_interval
0        2020-01-01 00:28:15        00:00 - 00:30
1        2020-01-01 00:35:39        00:30 - 01:00
2        2020-01-01 00:47:41        00:30 - 01:00
3        2020-01-01 00:55:23        00:30 - 01:00
4        2020-01-01 00:01:58        00:00 - 00:30
...                      ...                  ...
6405003  2020-01-31 22:51:00        22:30 - 23:00
6405004  2020-01-31 22:10:00        22:00 - 22:30
6405005  2020-01-31 22:50:07        22:30 - 23:00
6405006  2020-01-31 22:25:53        22:00 - 22:30
6405007  2020-01-31 22:44:00        22:30 - 23:00

[6405008 rows x 2 columns]

In [ ]:
#

**8) For each interval, determine the average number of passengers and the average fare amount.**

In [7]:
import pandas as pd

# Si carica il dataset
df = pd.read_csv("data.csv", low_memory=False)

# Si converte la colonna pickup datetime in formato datetime
df["tpep_pickup_datetime"] = pd.to_datetime(df["tpep_pickup_datetime"])

# Si creano intervalli di 30 minuti
def cluster_pickup_time(dt):
    hour = dt.hour
    minute = dt.minute
    if minute < 30:
        return f"{hour:02d}:00 - {hour:02d}:30"
    else:
        next_hour = (hour + 1) % 24
        return f"{hour:02d}:30 - {next_hour:02d}:00"

df["pickup_time_interval"] = df["tpep_pickup_datetime"].apply(cluster_pickup_time)

# Si calcola la media passeggeri e tariffa per intervallo
interval_stats = df.groupby("pickup_time_interval").agg(
    avg_passengers=("passenger_count", "mean"),
    avg_fare_amount=("fare_amount", "mean")
).reset_index()

# Si arrotondano i risultati a 2 decimali
interval_stats["avg_passengers"] = interval_stats["avg_passengers"].round(2)
interval_stats["avg_fare_amount"] = interval_stats["avg_fare_amount"].round(2)

# Si mostrano i risultati
print(interval_stats)

   pickup_time_interval  avg_passengers  avg_fare_amount
0         00:00 - 00:30            1.57            13.68
1         00:30 - 01:00            1.58            13.30
2         01:00 - 01:30            1.58            12.77
3         01:30 - 02:00            1.59            12.33
4         02:00 - 02:30            1.59            12.16
5         02:30 - 03:00            1.59            12.13
6         03:00 - 03:30            1.58            12.61
7         03:30 - 04:00            1.59            13.27
8         04:00 - 04:30            1.58            14.58
9         04:30 - 05:00            1.52            17.12
10        05:00 - 05:30            1.48            19.37
11        05:30 - 06:00            1.41            16.59
12        06:00 - 06:30            1.39            15.46
13        06:30 - 07:00            1.38            12.97
14        07:00 - 07:30            1.42            12.74
15        07:30 - 08:00            1.45            12.09
16        08:00 - 08:30            1.46            12.21
17        08:30 - 09:00            1.44            12.04
18        09:00 - 09:30            1.45            12.25
19        09:30 - 10:00            1.47            12.05
20        10:00 - 10:30            1.49            12.23
21        10:30 - 11:00            1.49            12.02
22        11:00 - 11:30            1.50            12.09
23        11:30 - 12:00            1.50            11.84
24        12:00 - 12:30            1.50            12.12
25        12:30 - 13:00            1.50            12.22
26        13:00 - 13:30            1.51            12.58
27        13:30 - 14:00            1.51            12.77
28        14:00 - 14:30            1.51            13.20
29        14:30 - 15:00            1.51            13.01
30        15:00 - 15:30            1.53            13.16
31        15:30 - 16:00            1.52            13.15
32        16:00 - 16:30            1.52            13.55
33        16:30 - 17:00            1.51            13.16
34        17:00 - 17:30            1.51            12.91
35        17:30 - 18:00            1.52            12.39
36        18:00 - 18:30            1.52            12.30
37        18:30 - 19:00            1.53            12.01
38        19:00 - 19:30            1.53            11.98
39        19:30 - 20:00            1.53            12.11
40        20:00 - 20:30            1.53            12.61
41        20:30 - 21:00            1.54            12.81
42        21:00 - 21:30            1.55            12.84
43        21:30 - 22:00            1.56            12.66
44        22:00 - 22:30            1.57            12.91
45        22:30 - 23:00            1.57            13.28
46        23:00 - 23:30            1.57            13.40
47        23:30 - 00:00            1.57            13.33

In [ ]:
#

**9) For each payment type and each interval, determine the average fare amount**

In [8]:
import pandas as pd

# Si carica il dataset
df = pd.read_csv("data.csv", low_memory=False)

# Si converte la colonna pickup datetime
df["tpep_pickup_datetime"] = pd.to_datetime(df["tpep_pickup_datetime"])

# Si crea la colonna pickup_time_interval
def cluster_pickup_time(dt):
    hour = dt.hour
    minute = dt.minute
    if minute < 30:
        return f"{hour:02d}:00 - {hour:02d}:30"
    else:
        next_hour = (hour + 1) % 24
        return f"{hour:02d}:30 - {next_hour:02d}:00"

if "pickup_time_interval" not in df.columns:
    df["pickup_time_interval"] = df["tpep_pickup_datetime"].apply(cluster_pickup_time)

# Si calcola la media della fare_amount per payment_type e intervallo
payment_interval_stats = df.groupby(["payment_type", "pickup_time_interval"]).agg(
    avg_fare_amount=("fare_amount", "mean")
).reset_index()

# Si arrotonda il risultato
payment_interval_stats["avg_fare_amount"] = payment_interval_stats["avg_fare_amount"].round(2)

# Si mostrano i risultati
print(payment_interval_stats)

     payment_type pickup_time_interval  avg_fare_amount
0             1.0        00:00 - 00:30            13.87
1             1.0        00:30 - 01:00            13.47
2             1.0        01:00 - 01:30            12.82
3             1.0        01:30 - 02:00            12.36
4             1.0        02:00 - 02:30            12.01
..            ...                  ...              ...
188           4.0        22:00 - 22:30             1.53
189           4.0        22:30 - 23:00            -0.79
190           4.0        23:00 - 23:30            -0.35
191           4.0        23:30 - 00:00            -2.75
192           5.0        17:30 - 18:00             0.00

[193 rows x 3 columns]

In [ ]:
#

**10) For each payment type, determine the interval when the average fare amount is maximum**

In [9]:
import pandas as pd

# Si caricano i dati
df = pd.read_csv("data.csv", low_memory=False)

# Ci si assicura che il datetime sia correttamente formattato
df["tpep_pickup_datetime"] = pd.to_datetime(df["tpep_pickup_datetime"])

# Si crea la colonna 'pickup_time_interval'
def cluster_pickup_time(dt):
    hour = dt.hour
    minute = dt.minute
    if minute < 30:
        return f"{hour:02d}:00 - {hour:02d}:30"
    else:
        next_hour = (hour + 1) % 24
        return f"{hour:02d}:30 - {next_hour:02d}:00"

if "pickup_time_interval" not in df.columns:
    df["pickup_time_interval"] = df["tpep_pickup_datetime"].apply(cluster_pickup_time)

# Si calcola la media della fare_amount per ogni payment_type e intervallo
grouped = df.groupby(["payment_type", "pickup_time_interval"]).agg(
    avg_fare_amount=("fare_amount", "mean")
).reset_index()

# Si trova per ogni payment_type l'intervallo con il massimo valore medio
max_fare_per_type = grouped.loc[grouped.groupby("payment_type")["avg_fare_amount"].idxmax()]

# Si arrotonda il risultato
max_fare_per_type["avg_fare_amount"] = max_fare_per_type["avg_fare_amount"].round(2)

# Si mostra il risultato
print(max_fare_per_type)

     payment_type pickup_time_interval  avg_fare_amount
10            1.0        05:00 - 05:30            21.26
58            2.0        05:00 - 05:30            14.85
110           3.0        07:00 - 07:30            10.95
154           4.0        05:00 - 05:30             6.63
192           5.0        17:30 - 18:00             0.00

In [ ]:
#

**11) For each payment type, determine the interval when the overall ratio between the tip and the fare amounts is maximum**

In [10]:
import pandas as pd

# Si carica il dataset
df = pd.read_csv("data.csv", low_memory=False)

# Ci si assicura che il campo datetime sia in formato datetime
df["tpep_pickup_datetime"] = pd.to_datetime(df["tpep_pickup_datetime"])

# Si crea la colonna pickup_time_interval (30 minuti)
def cluster_pickup_time(dt):
    hour = dt.hour
    minute = dt.minute
    if minute < 30:
        return f"{hour:02d}:00 - {hour:02d}:30"
    else:
        next_hour = (hour + 1) % 24
        return f"{hour:02d}:30 - {next_hour:02d}:00"

df["pickup_time_interval"] = df["tpep_pickup_datetime"].apply(cluster_pickup_time)

# Si filtrano le righe che contengono valori validi
df = df[(df["fare_amount"] > 0) & df["tip_amount"].notnull()]

# Si raggruppa per payment_type e intervalli di tempo e si calcola la somma delle tip e delle fare
grouped = df.groupby(["payment_type", "pickup_time_interval"]).agg(
    total_tip=("tip_amount", "sum"),
    total_fare=("fare_amount", "sum")
).reset_index()

# Si calcola il rapporto totale tip/fare per ogni gruppo
grouped["tip_fare_ratio"] = grouped["total_tip"] / grouped["total_fare"]

# Si trova l'intervallo con il rapporto massimo per ciascun payment_type
max_ratios = grouped.loc[grouped.groupby("payment_type")["tip_fare_ratio"].idxmax()]

# Si arrotonda per leggibilità
max_ratios['tip_fare_ratio_percent'] = (max_ratios['tip_fare_ratio'] * 100).round(2).astype(str) + '%'

# Si Visualizza il risultato
print(max_ratios[["payment_type", "pickup_time_interval", "tip_fare_ratio_percent"]])

     payment_type pickup_time_interval tip_fare_ratio_percent
37            1.0        18:30 - 19:00                  24.3%
68            2.0        10:00 - 10:30                  0.01%
138           3.0        21:00 - 21:30                  0.55%
164           4.0        10:00 - 10:30                  0.19%

In [ ]:
#

**12) Find the location with the highest average fare amount**

In [1]:
import pandas as pd

# Si caricano i dati
df = pd.read_csv("data.csv", low_memory=False)

# Si filtrano le righe con valori validi
df = df[df["fare_amount"] > 0]

# Si calcola la media per ciascuna location
avg_fare_by_location = df.groupby("PULocationID")["fare_amount"].mean().reset_index()

# Si trova la riga con il valore massimo e si crea una copia
max_avg_fare = avg_fare_by_location.loc[avg_fare_by_location["fare_amount"].idxmax()].copy()

# Si arrotonda in modo sicuro
max_avg_fare["fare_amount"] = round(max_avg_fare["fare_amount"], 2)

# Si mostra il risultato
print(f"Location con la media più alta del fare amount:")
print(f"PULocationID: {int(max_avg_fare["PULocationID"])}, Average Fare: ${max_avg_fare["fare_amount"]}")

Location con la media più alta del fare amount:
PULocationID: 204, Average Fare: $107.0

In [ ]:
#

**13) Build a new dataframe (called common) where, for each pickup location we keep all trips to the 5 most common destinations (i.e. each pickup location can have different common destinations).**

In [2]:
import pandas as pd

# Si caricano i dati
df = pd.read_csv("data.csv", low_memory=False)

# Si crea una funzione per ottenere le 5 destinazioni più comuni da una pickup location
def top_5_destinations(df):
    return (
        df.groupby(["PULocationID", "DOLocationID"])
          .size()
          .reset_index(name="count")
    )

# Si calcola la frequenza per tutte le coppie pickup-dropoff
pair_counts = top_5_destinations(df)

# Si ordinano quest'ultime per count decrescente all'interno di ogni PULocationID
pair_counts = pair_counts.sort_values(["PULocationID", "count"], ascending=[True, False])

# Si prendono le prime 5 DOLocationID per ciascun PULocationID
top5_pairs = pair_counts.groupby("PULocationID").head(5)

# Si fa il merge con il dataset originale per ottenere solo i viaggi corrispondenti
common = df.merge(top5_pairs[["PULocationID", "DOLocationID"]], on=["PULocationID", "DOLocationID"])

# Si mostra il nuovo dataframe "common"
print("Nuovo DataFrame 'common' con le 5 destinazioni più comuni per ciascuna pickup location:")
print(common)

Nuovo DataFrame 'common' con le 5 destinazioni più comuni per ciascuna pickup location:
         VendorID tpep_pickup_datetime tpep_dropoff_datetime  passenger_count  \
0             1.0  2020-01-01 00:28:15   2020-01-01 00:33:03              1.0
1             1.0  2020-01-01 00:35:39   2020-01-01 00:43:04              1.0
2             1.0  2020-01-01 00:47:41   2020-01-01 00:53:52              1.0
3             1.0  2020-01-01 00:55:23   2020-01-01 01:00:14              1.0
4             2.0  2020-01-01 00:01:58   2020-01-01 00:04:16              1.0
...           ...                  ...                   ...              ...
1964557       NaN  2020-01-31 06:41:00   2020-01-31 07:17:00              NaN
1964558       NaN  2020-01-31 06:04:00   2020-01-31 06:07:00              NaN
1964559       NaN  2020-01-31 06:06:57   2020-01-31 06:57:15              NaN
1964560       NaN  2020-01-31 21:14:39   2020-01-31 21:18:38              NaN
1964561       NaN  2020-01-31 21:46:00   2020-01-31 21:53:00              NaN

         trip_distance  RatecodeID store_and_fwd_flag  PULocationID  \
0                 1.20         1.0                  N           238
1                 1.20         1.0                  N           239
2                 0.60         1.0                  N           238
3                 0.80         1.0                  N           238
4                 0.00         1.0                  N           193
...                ...         ...                ...           ...
1964557          12.08         NaN                NaN            32
1964558           0.15         NaN                NaN            81
1964559          19.76         NaN                NaN           191
1964560           0.41         NaN                NaN           143
1964561           0.79         NaN                NaN           263

         DOLocationID  payment_type  fare_amount  extra  mta_tax  tip_amount  \
0                 239           1.0         6.00   3.00      0.5        1.47
1                 238           1.0         7.00   3.00      0.5        1.50
2                 238           1.0         6.00   3.00      0.5        1.00
3                 151           1.0         5.50   0.50      0.5        1.36
4                 193           2.0         3.50   0.50      0.5        0.00
...               ...           ...          ...    ...      ...         ...
1964557           145           NaN        34.92   2.75      0.5        0.00
1964558            51           NaN        30.66   2.75      0.5        0.00
1964559           261           NaN        58.50   2.75      0.0        0.00
1964560           143           NaN        13.88   5.50      0.5        0.00
1964561           263           NaN        26.08   2.75      0.5        0.00

         tolls_amount  improvement_surcharge  total_amount  \
0                0.00                    0.3         11.27
1                0.00                    0.3         12.30
2                0.00                    0.3         10.80
3                0.00                    0.3          8.16
4                0.00                    0.3          4.80
...               ...                    ...           ...
1964557          6.12                    0.3         44.59
1964558          0.00                    0.3         34.21
1964559          0.00                    0.3         61.55
1964560          0.00                    0.3         20.18
1964561          0.00                    0.3         29.63

         congestion_surcharge
0                         2.5
1                         2.5
2                         2.5
3                         0.0
4                         0.0
...                       ...
1964557                   0.0
1964558                   0.0
1964559                   0.0
1964560                   0.0
1964561                   0.0

[1964562 rows x 18 columns]

In [ ]:
#

**14) On the common dataframe, for each payment type and each interval, determine the average fare amount**

In [3]:
import pandas as pd

# Ci si assicura che il campo datetime sia corretto
common["tpep_pickup_datetime"] = pd.to_datetime(common["tpep_pickup_datetime"])

# Si creano gli intervalli di 30 minuti
def cluster_pickup_time(dt):
    hour = dt.hour
    minute = dt.minute
    if minute < 30:
        return f"{hour:02d}:00 - {hour:02d}:30"
    else:
        next_hour = (hour + 1) % 24
        return f"{hour:02d}:30 - {next_hour:02d}:00"

common["pickup_time_interval"] = common["tpep_pickup_datetime"].apply(cluster_pickup_time)

# Si filtrano le righe con fare_amount valido (> 0)
filtered = common[common["fare_amount"] > 0]

# Si calcola la media del fare per payment_type e intervallo
avg_fare = (
    filtered.groupby(["payment_type", "pickup_time_interval"])["fare_amount"]
    .mean()
    .reset_index()
)

# Si arrotonda per leggibilità
avg_fare["fare_amount"] = avg_fare["fare_amount"].apply(lambda x: f"{x:.2f}$")

# Si mostra il risultato
print("Media fare_amount per payment_type e intervallo (solo viaggi comuni):")
print(avg_fare)

Media fare_amount per payment_type e intervallo (solo viaggi comuni):
     payment_type pickup_time_interval fare_amount
0             1.0        00:00 - 00:30       8.59$
1             1.0        00:30 - 01:00       8.70$
2             1.0        01:00 - 01:30       8.50$
3             1.0        01:30 - 02:00       8.03$
4             1.0        02:00 - 02:30       7.95$
..            ...                  ...         ...
187           4.0        21:30 - 22:00      14.91$
188           4.0        22:00 - 22:30       9.15$
189           4.0        22:30 - 23:00      12.10$
190           4.0        23:00 - 23:30       7.30$
191           4.0        23:30 - 00:00       8.48$

[192 rows x 3 columns]

In [ ]:
#

**15) Compute the difference of the average fare amount computed in the previous point with those computed at point 9**

In [5]:
import pandas as pd

# Ci si assicura che il datetime sia in formato corretto sul df completo
df["tpep_pickup_datetime"] = pd.to_datetime(df["tpep_pickup_datetime"])

# Si definisce la funzione per creare gli intervalli di 30 minuti
def cluster_pickup_time(dt):
    hour = dt.hour
    minute = dt.minute
    if minute < 30:
        return f"{hour:02d}:00 - {hour:02d}:30"
    else:
        next_hour = (hour + 1) % 24
        return f"{hour:02d}:30 - {next_hour:02d}:00"

if "pickup_time_interval" not in df.columns:
    df["pickup_time_interval"] = df["tpep_pickup_datetime"].apply(cluster_pickup_time)

# Si filtrano solo le righe valide
filtered_full = df[df["fare_amount"] > 0]

# Si calcola la media del fare per payment_type e intervallo (dataset completo)
avg_fare_full = (
    filtered_full.groupby(["payment_type", "pickup_time_interval"])["fare_amount"]
    .mean()
    .reset_index()
)
avg_fare_full.rename(columns={"fare_amount": "avg_fare_full"}, inplace=True)

# --- Punto 14: media del fare_amount per payment_type e intervallo sul dataframe common ---

# Ci si assicura che il datetime sia in formato corretto sul dataframe common
common["tpep_pickup_datetime"] = pd.to_datetime(common["tpep_pickup_datetime"])
if "pickup_time_interval" not in common.columns:
    common["pickup_time_interval"] = common["tpep_pickup_datetime"].apply(cluster_pickup_time)

# Si filtra solo le righe valide
filtered_common = common[common["fare_amount"] > 0]

# Si calcola la media fare per payment_type e intervallo (solo viaggi comuni)
avg_fare_common = (
    filtered_common.groupby(["payment_type", "pickup_time_interval"])["fare_amount"]
    .mean()
    .reset_index()
)
avg_fare_common.rename(columns={"fare_amount": "avg_fare_common"}, inplace=True)

# --- Calcolo della differenza tra avg_fare_common e avg_fare_full ---

# Si esegue la merge tra i due dataframe sulle colonne payment_type e pickup_time_interval
fare_comparison = pd.merge(
    avg_fare_common,
    avg_fare_full,
    on=["payment_type", "pickup_time_interval"],
    how="inner"
)

# Si effettua il calcolo della differenza (common - full)
fare_comparison["fare_diff"] = fare_comparison["avg_fare_common"] - fare_comparison["avg_fare_full"]

# Si arrotonda per chiarezza
fare_comparison["avg_fare_common"] = fare_comparison["avg_fare_common"].round(2)
fare_comparison["avg_fare_full"] = fare_comparison["avg_fare_full"].round(2)
fare_comparison["fare_diff"] = fare_comparison["fare_diff"].round(2)

# Si mostra il risultato
print("Differenza media fare_amount (common - full) per payment_type e intervallo:")
print(fare_comparison)

Differenza media fare_amount (common - full) per payment_type e intervallo:
     payment_type pickup_time_interval  avg_fare_common  avg_fare_full  \
0             1.0        00:00 - 00:30             8.59          13.87
1             1.0        00:30 - 01:00             8.70          13.47
2             1.0        01:00 - 01:30             8.50          12.83
3             1.0        01:30 - 02:00             8.03          12.36
4             1.0        02:00 - 02:30             7.95          12.01
..            ...                  ...              ...            ...
187           4.0        21:30 - 22:00            14.91          15.96
188           4.0        22:00 - 22:30             9.15          13.52
189           4.0        22:30 - 23:00            12.10          15.86
190           4.0        23:00 - 23:30             7.30          14.27
191           4.0        23:30 - 00:00             8.48          14.78

     fare_diff
0        -5.28
1        -4.77
2        -4.33
3        -4.33
4        -4.06
..         ...
187      -1.06
188      -4.38
189      -3.77
190      -6.97
191      -6.30

[192 rows x 5 columns]

In [ ]:
#

**16) Compute the ratio between the differences computed in the previous point and those computed in point 9. Note: you have to compute a ratio for each pair (payment type, interval).**

In [6]:
# Calcolo del rapporto tra la differenza e la media fare completa (punto 9)

# Si evitano divisioni per zero sostituendo 0 con NaN temporaneamente
fare_comparison["fare_ratio"] = fare_comparison.apply(
    lambda row: row["fare_diff"] / row["avg_fare_full"] if row["avg_fare_full"] != 0 else None,
    axis=1
)

# Si arrotonda a 4 decimali per chiarezza
fare_comparison["fare_ratio"] = fare_comparison["fare_ratio"].round(4)

# Si visualizza il risultato
print("Rapporto tra la differenza media (common - full) e la media completa del fare_amount:")
print(fare_comparison[["payment_type", "pickup_time_interval", "fare_diff", "avg_fare_full", "fare_ratio"]])

Rapporto tra la differenza media (common - full) e la media completa del fare_amount:
     payment_type pickup_time_interval  fare_diff  avg_fare_full  fare_ratio
0             1.0        00:00 - 00:30      -5.28          13.87     -0.3807
1             1.0        00:30 - 01:00      -4.77          13.47     -0.3541
2             1.0        01:00 - 01:30      -4.33          12.83     -0.3375
3             1.0        01:30 - 02:00      -4.33          12.36     -0.3503
4             1.0        02:00 - 02:30      -4.06          12.01     -0.3381
..            ...                  ...        ...            ...         ...
187           4.0        21:30 - 22:00      -1.06          15.96     -0.0664
188           4.0        22:00 - 22:30      -4.38          13.52     -0.3240
189           4.0        22:30 - 23:00      -3.77          15.86     -0.2377
190           4.0        23:00 - 23:30      -6.97          14.27     -0.4884
191           4.0        23:30 - 00:00      -6.30          14.78     -0.4263

[192 rows x 5 columns]

In [ ]:
#

**17) Build chains of trips. Two trips are consecutive in a chain if (a) they have the same VendorID, (b) the pickup location of the second trip is also the dropoff location of the first trip, (c) the pickup time of the second trip is after the dropoff time of the first trip, and (d) the pickup time of the second trip is at most 2 minutes later than the dropoff time of the first trip.**

In [7]:
import pandas as pd

# Assicuriamoci che i datetime siano corretti
df["tpep_pickup_datetime"] = pd.to_datetime(df["tpep_pickup_datetime"])
df["tpep_dropoff_datetime"] = pd.to_datetime(df["tpep_dropoff_datetime"])

# Ordiniamo per VendorID e pickup/dropoff datetime
df = df.sort_values(["VendorID", "tpep_pickup_datetime"]).reset_index(drop=True)

# Copie separate per il merge
df_current = df.copy()
df_next = df.copy()

# Rinominiamo le colonne di df_next per distinguerle
df_next = df_next.rename(columns={
    "tpep_pickup_datetime": "next_pickup_datetime",
    "PULocationID": "next_PULocationID",
    "DOLocationID": "next_DOLocationID"
})

# Ordiniamo per merge_asof
df_current = df_current.sort_values(["VendorID", "tpep_dropoff_datetime"])
df_next = df_next.sort_values(["VendorID", "next_pickup_datetime"])

# Applichiamo merge_asof con tolleranza di 2 minuti
merged = pd.merge_asof(
    df_current,
    df_next,
    left_on="tpep_dropoff_datetime",
    right_on="next_pickup_datetime",
    by="VendorID",
    direction="forward",
    tolerance=pd.Timedelta("2min")
)

# Filtriamo solo i casi in cui il dropoff della prima corsa coincide col pickup della successiva
chains = merged[merged["DOLocationID"] == merged["next_PULocationID"]]

# Visualizziamo le catene valide
print("Catene trovate:")
print(chains[[
    "VendorID",
    "tpep_pickup_datetime", "PULocationID", "DOLocationID", "tpep_dropoff_datetime",
    "next_pickup_datetime", "next_PULocationID", "next_DOLocationID"
]])

ValueError: left keys must be sorted

In [ ]:
#